version: '3'

services:
  app:
    build:
        context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000 "
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=12345
    depends_on:
    - db
    restart: always


  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - '5342:5342'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
