# Generated by Django 4.1.4 on 2023-03-12 08:42

import django.db.models.deletion
from django.db import migrations, models


def populate_initial_languages(apps, schema_editor):
    Language = apps.get_model('application', 'Language')
    Language.objects.create(
        code='en',
        name='English',
    )
    Language.objects.create(
        code='ru',
        name='Russian',
    )


def populate_language_fks(apps, schema_editor):
    Language = apps.get_model('application', 'Language')
    Game = apps.get_model('application', 'Game')
    AutoAnswer = apps.get_model('application', 'autoanswer')
    Task = apps.get_model('application', 'task')
    mapping = {lang.code: lang for lang in Language.objects.all()}
    Game.objects.update(language_id=mapping['ru'].id)
    for code, lang in mapping.items():
        AutoAnswer.objects.filter(language_str=code).update(language=lang)
        Task.objects.filter(language_str=code).update(language=lang)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        # create language model
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RunPython(populate_initial_languages, migrations.RunPython.noop),
        # keep exising string fields for language
        migrations.RenameField(
            model_name='autoanswer',
            old_name='language',
            new_name='language_str',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='language',
            new_name='language_str',
        ),
        # add FKs
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='application.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoanswer',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='auto_answers', to='application.language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                    to='application.language'),
            preserve_default=False,
        ),
        # migrate from str to language FKs
        migrations.RunPython(populate_language_fks, migrations.RunPython.noop),
        # drop redundant fields
        migrations.RemoveField(
            model_name='autoanswer',
            name='language_str',
        ),
        migrations.RemoveField(
            model_name='task',
            name='language_str',
        ),
        # make FKs not null
        migrations.AlterField(
            model_name='autoanswer',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_answers',
                                    to='application.language'),
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games',
                                    to='application.language'),
        ),
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                    to='application.language'),
        ),
    ]
