# Generated by Django 4.1.4 on 2023-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_players_unique_for_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='likes_cnt',
            field=models.IntegerField(default=0, verbose_name='likes count'),
        ),
    ]
