# Generated by Django 4.1.4 on 2023-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_variant_likes_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_variants', to='application.player'),
        ),
    ]
