# Generated by Django 4.1.7 on 2023-04-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_task_auto_created_variant_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='likes_cnt',
        ),
    ]
