# Generated by Django 4.1.7 on 2023-04-02 13:45

from django.db import migrations, models

import application.services.basics


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_variant_likes_cnt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('stage', application.services.basics.GameStage['finished']), _negated=True), fields=('code',), name='unique_active_game_code'),
        ),
    ]
